debug: true
Database:
   Host: localhost
   Port: 3306
   User: ChickenLeague
   Password: password
   Database: ChickenLeague
Arenas: 4
Description: "Nutze die Schaufeln in deiner Hotbar, welche verschiedene Knockbackverzauberungen haben, um ins gegnerische Tor zu treffen. Die orangenen Teppiche geben dir Speed und besondere Items"
Bats:
   Wood:
      Speed: 0.3
   Gold:
      Speed: 0.22
   Diamond:
      Speed: 0.15
Spawn:
   X: 100
   Y: 100
   Z: 100
   Yaw: 0
   Pitch: 0
   World: world
ONE_VS_ONE:
   Team1:
      Goal: 
         X1: -26
         Z1: -2
         X2: -27
         Z2: 2
      Spawn1:
         X: 15.5
         Y: 65
         Z: 0.5
         Yaw: 90
         Pitch: 0
   Team2:
      Goal: 
         X1: 26
         Z1: -2
         X2: 27
         Z2: 2
      Spawn1:
         X: -14.5
         Y: 65
         Z: 0.5
         Yaw: -90
         Pitch: 0
   Middle:
      X: 0.5
      Y: 65
      Z: 0.5
      Pitch: 0 
      Yaw: 0
   Edges:
      First:
         X: -24
         Z: 15
      Second:
         X: 25
         Z: -14
   ItemSpawns:
   - "-25.5/65/15.5"
   - "-24.5/65/-14.5"
   - "14.5/65/0.5"
   - "0.5/65/-14.5"
   - "0.5/65/0.5"
   - "0.5/65/15.5"
   - "15.5/65/0.5"
   - "25.5/65/-14.5"
   - "25.5/65/15.5"
THREE_VS_THREE:
   Team1:
      Goal: 
         X1: 3
         Z1: -55
         X2: -3
         Z2: -55
      Spawn1:
         X: 6.5
         Y: 65
         Z: -5.5
         Yaw: 44
         Pitch: 11
      Spawn2:
         X: 0.5
         Y: 65
         Z: -8.5
         Yaw: 0 
         Pitch: 11 
      Spawn3:
         X: -5.5
         Y: 65
         Z: -5.5
         Yaw: -44
         Pitch: 11
   Team2:
      Goal: 
         X1: 3
         Z1: 58
         X2: -3
         Z2: 58
      Spawn1:
         X: 6.5
         Y: 65
         Z: 6.5
         Yaw: 135
         Pitch: 11
      Spawn2:
         X: 0.5
         Y: 65
         Z: 9.5
         Yaw: 180
         Pitch: 11 
      Spawn3:
         X: -5.5
         Y: 65
         Z: 6.5
         Yaw: -134
         Pitch: 11
   Middle:
      X: 0.5
      Y: 65
      Z: 0.5
      Pitch: 0
      Yaw: 90
   Edges:
      First:
         X: -44
         Z: 56
      Second:
         X: 45
         Z: -53
   ItemSpawns:
      - "-44.5/65/-53.5"
      - "45.5/65/-53.5"
      - "0.5/65/-43.5"
      - "-19.5/65/-38.5"
      - "20.5/65/-38.5"
      - "45.5/65/0.5"
      - "0.5/65/0.5"
      - "-44.5/65/0.5"
      - "20.5/65/41.5"
      - "19.5/65/41.5"
      - "0.5/65/46.5"
      - "45.5/65/56.5"
      - "-44.5/65/56.5"
FIVE_VS_FIVE:
   Team1:
      Goal: 
         X1: 3
         Z1: -55
         X2: -3
         Z2: -55
      Spawn1:
         X: 6.5
         Y: 65
         Z: -5.5
         Yaw: 44
         Pitch: 11
      Spawn2:
         X: 0.5
         Y: 65
         Z: -8.5
         Yaw: 0 
         Pitch: 11 
      Spawn3:
         X: -5.5
         Y: 65
         Z: -5.5
         Yaw: -44
         Pitch: 11
      Spawn4:
         X: 8.5
         Y: 65
         Z: -2.5
         Yaw: 70
         Pitch: 11
      Spawn5:
         X: -7.5
         Y: 65
         Z: -2.5
         Yaw: 70
         Pitch: 11
   Team2:
      Goal: 
         X1: 3
         Z1: 58
         X2: -3
         Z2: 58
      Spawn1:
         X: 6.5
         Y: 65
         Z: 6.5
         Yaw: 135
         Pitch: 11
      Spawn2:
         X: 0.5
         Y: 65
         Z: 9.5
         Yaw: 180
         Pitch: 11 
      Spawn3:
         X: -5.5
         Y: 65
         Z: 6.5
         Yaw: -134
         Pitch: 11
      Spawn4:
         X: 7.5
         Y: 65
         Z: 3.5
         Yaw:  -110
         Pitch: 11
      Spawn5:
         X: 8.5
         Y: 65
         Z: 3.5
         Yaw: -250
         Pitch: 11 
   Middle:
      X: 0.5
      Y: 65
      Z: 0.5
      Pitch: 0
      Yaw: 90
   Edges:
      First:
         X: -45
         Z: 57
      Second:
         X: 46
         Z: -54
   ItemSpawns:
      - "-44.5/65/-53.5"
      - "45.5/65/-53.5"
      - "0.5/65/-43.5"
      - "-19.5/65/-38.5"
      - "20.5/65/-38.5"
      - "45.5/65/0.5"
      - "0.5/65/0.5"
      - "-44.5/65/0.5"
      - "20.5/65/41.5"
      - "19.5/65/41.5"
      - "0.5/65/46.5"
      - "45.5/65/56.5"
      - "-44.5/65/56.5"
   