name: ChickenLeagueHost
main: de.petropia.chickenLeagueHost.ChickenLeagueHost
author: Professor_Sam
softdepend:
- Multiverse-Core
version: ${project.version}
api-version: 1.19
commands:
   ChickenLeague:
      description: Manage ChickenLeague
   Start:
      description: Startet das Spiel