debug: true
Database:
   Host: localhost
   Port: 3306
   User: ChickenLeague
   Password: password
   Database: ChickenLeague
Portal:
   ONE_VS_ONE:
      X1: -93
      Z1: -84
      X2: -93
      Z2: -88
   THREE_VS_THREE:
      X1: -69
      Z1: -84
      X2: -69
      Z2: -88